[package]
name = "paraseq"
version = "0.6.0"
edition = "2021"
authors = ["Noam Teyssier"]
keywords = ["fasta", "fastq", "parser", "parallel", "paired"]
license = "MIT"
repository = "https://github.com/noamteyssier/paraseq"
description = "A minimal-copy parser for FASTA and FASTQ files built for paired parallel processing."
readme = "README.md"
documentation = "https://docs.rs/paraseq"

[dependencies]
anyhow = { version = "1.0.104", optional = true }
crossbeam-channel = "0.5.17"
either = "1.18.0"
env_logger = "0.11.11"
fearless_simd = "1.0.0-rc.1"
itertools = "0.15.0"
log = "0.4.34"
memchr = "2.8.3"
niffler = { version = "3.0.1", optional = true, default-features = false }
num_cpus = "1.17.0"
reqwest = { version = "0.13.5", optional = true, features = ["blocking"] }
rust-htslib = { version = "1.0.1", default-features = false, optional = true }
smallvec = "1.16.1"
thiserror = "2.0.20"

[features]
default = ["anyhow", "niffler", "niffler/default"]
anyhow = ["dep:anyhow"]
niffler = ["dep:niffler"]
htslib = ["dep:rust-htslib"]
url = ["dep:reqwest", "dep:niffler"]
ssh = []
gcs = []

[dev-dependencies]
clap = { version = "4.6.7", features = ["derive"] }
niffler = "3.0.1"

[[example]]
name = "htslib"
required-features = ["htslib"]

[[example]]
name = "url"
required-features = ["url"]

[[example]]
name = "ssh"
required-features = ["ssh"]

[[example]]
name = "gcs"
required-features = ["gcs"]
