name: Rust

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    needs: [build, test, url]
    name: CI
    runs-on: "ubuntu-latest"
    steps:
      - name: Done
        run: exit 0

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v7
      - name: Build
        run: cargo build --verbose
      - name: Build no default features
        run: cargo build --verbose --no-default-features
      - name: Build examples
        run: cargo build --verbose --examples

  test:
    name: Test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --verbose

  url:
    name: Test URL
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - name: Run URL example
        run: cargo run --release --example url
