name: Rust

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    needs: [build, test, style, examples, url]
    name: CI
    runs-on: "ubuntu-latest"
    steps:
      - name: Done
        run: exit 0

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v7
      - name: Build
        run: cargo build --verbose
      - name: Build no default features
        run: cargo build --verbose --no-default-features
      - name: Build examples
        run: cargo build --verbose --examples

  test:
    name: Test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --verbose
      - name: Test pool feature
        run: cargo test --verbose --features pool

  style:
    name: Style
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - name: Check style
        run: cargo fmt --check
      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  examples:
    name: Run Examples
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - name: Build examples
        run: cargo build --examples
      - name: naive
        run: cargo run --quiet --example naive -- data/sample.fastq
      - name: multiline_fasta
        run: cargo run --quiet --example multiline_fasta
      - name: reloading
        run: cargo run --quiet --example reloading -- data/sample.fastq --prefill 3
      - name: parallel
        run: cargo run --quiet --example parallel -- data/sample.fastq
      - name: parallel_closure
        run: cargo run --quiet --example parallel_closure -- data/sample.fastq
      - name: paired_parallel
        run: cargo run --quiet --example paired_parallel -- data/r1.fastq data/r2.fastq
      - name: interleaved
        run: cargo run --quiet --example interleaved -- data/interleaved.fastq
      - name: range_parallel
        run: cargo run --quiet --example range_parallel -- data/sample.fastq --start 10 --end 30
      - name: reloading_parallel
        run: cargo run --quiet --example reloading_parallel -- data/sample.fastq --prefill 3
      - name: multi_parallel
        run: cargo run --quiet --example multi_parallel -- data/r1.fastq data/r2.fastq data/r3.fastq
      - name: multi_interleaved
        run: cargo run --quiet --example multi_interleaved -- data/r123.fastq --arity 3
      - name: collection (single)
        run: cargo run --quiet --example collection -- data/sample.fastq
      - name: collection (paired)
        run: cargo run --quiet --example collection -- data/r1.fastq data/r2.fastq --paired
      - name: fastx
        run: cargo run --quiet --example fastx -- data/sample.fastq --format fasta > /dev/null
      - name: read_write
        run: cargo run --quiet --example read_write -- data/sample.fastq.gz --format fastq > /dev/null

  url:
    name: Test URL
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - name: Run URL example
        run: cargo run --release --example url -F url

  htslib:
    name: Test HTSlib
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - name: htslib
        run: cargo run --quiet --example htslib -F htslib -- data/sample.bam --format fastq > /dev/null
      - name: htslib (paired)
        run: cargo run --quiet --example htslib -F htslib -- data/paired.bam --format fastq --paired > /dev/null
